### PR TITLE
Wrap SymEngine::ascii_art() and replace the current function

### LINKED ISSUE #13: Wrap SymEngine::ascii_art() and replace the current function
Refer https://github.com/symengine/symengine/pull/797/ and wrap it to replace the code [here](https://github.com/symengine/symengine.rb/blob/master/lib/symengine.rb#L6). It will also involve writing the C wrapper for the function.

### PR DESCRIPTION
**Pull request by codeworm96**
Fixed #13. Feedback needed.

### CODE REVIEW

**Comment by abinashmeher999** [comment]
Looks good. Could you add a test that checks if `SymEngine::ascii_art` returns a non-zero length string?

**Comment by codeworm96** [comment]
The test for ascii_art is added. It seems the test doesn't belong to any present spec file. So I created a new spec file for that. Is that ok?

**Comment by abinashmeher999** [comment]
It's ok. Better to rename it as `symengine_spec.rb` so that the other tests that belong directly to the module can go in there.

**Comment by codeworm96** [comment]
I have renamed it.

**Pull request merged**
