### PR TITLE
Add Windows Support

### PR DESCRIPTION
**Pull request by isuruf**
I'm using cmake to generate the Makefile in `extconf.rb` and let `DevKit` handle the rest.

Building the C extension goes fine, but using it causes errors.

CMake produces `lib\symengine\symengine.dll` and `lib\symengine\symengine.dll.a`. 
It is imported by `lib\symengine.rb` as `require 'symengine/symengine'
I get this error. 

```
C:/Users/dell/projects/symengine.rb/lib/symengine.rb:1:in `require': cannot load
 such file -- symengine/symengine (LoadError)
        from C:/Users/dell/projects/symengine.rb/lib/symengine.rb:1:in `<top (re
quired)>'
        from C:/Users/dell/projects/symengine.rb/spec/spec_helper.rb:16:in `requ
ire_relative'
        from C:/Users/dell/projects/symengine.rb/spec/spec_helper.rb:16:in `<top
 (required)>'
```

If I change the extension name from `.dll` to `.so` I get a different error.
```
C:/Users/dell/projects/symengine.rb/lib/symengine.rb:1:in `require': 126: The sp
ecified module could not be found.   - C:/Users/dell/projects/symengine.rb/lib/s
ymengine/symengine.so (LoadError)
        from C:/Users/dell/projects/symengine.rb/lib/symengine.rb:1:in `<top (re
quired)>'
        from C:/Users/dell/projects/symengine.rb/spec/spec_helper.rb:16:in `requ
ire_relative'
        from C:/Users/dell/projects/symengine.rb/spec/spec_helper.rb:16:in `<top
 (required)>'
```

@mohawkjohn @agarie @abinashmeher999

### CODE REVIEW

**Comment by isuruf** [comment]
Got it working. I forgot to add `gmp/bin` to path.
`Devkit` for `Ruby 1.9.3` has `GCC 4.5.2` which is older than the supported GCC version.
x64 tests still fail. I'll look into it later today or tomorrow.

https://ci.appveyor.com/project/isuruf/symengine-rb/build/17

**Comment by abinashmeher999** [comment]
Great!

**Comment by isuruf** [comment]
x64 tests fail probably because the GMP library for x64 was compiled with `gcc 4.9.1` whereas Devkit uses `gcc 4.7.2`

**Comment by isuruf** [comment]
Appveyor tests pass in my fork. Closing this to create a new PR with appveyor build.

**Pull request closed without merging**
