### PR TITLE
Fix development steps in README

### PR DESCRIPTION
**Pull request by codeworm96**
'symengine-0.0.0.gem' should be 'symengine-0.1.0.gem'

### CODE REVIEW

**Comment by abinashmeher999** [comment]
@codeworm96 Thanks for pointing it out.
@isuruf The one on RubyGems has version `0.0.2`. Same version should be maintained in the repo.

**Comment by isuruf** [comment]
@abinashmeher999, development version has to be ahead of the released version in RubyGems

**Comment by abinashmeher999** [comment]
`0.0.3` then?

**Comment by isuruf** [comment]
I think this is fine. When we want to make a new release we'll do it for 0.1.0 next

**Pull request merged**
